name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"

      - name: Instalar Poetry
        run: pipx install poetry

      - name: Configurar venv no projeto
        run: poetry config virtualenvs.in-project true

      - name: Instalar dependências
        run: poetry install

      - name: Ruff (lint)
        run: poetry run ruff check src tests

      - name: Ruff (format)
        run: poetry run ruff format --check src tests

      - name: Testes com cobertura
        run: poetry run pytest

      - name: Build da documentação
        run: poetry run mkdocs build --strict
